"""Self-contained interactive HTML report for compliance mapping results.

Produces a single ``.html`` file with embedded CSS and JS — no external
dependencies.  Two report modes in one page:

1. **Framework Gap Analysis** — one card per framework control showing
   which policy chunks support it and the LLM verdict.
2. **Policy Coverage** — one card per source document showing which
   framework controls each policy section satisfies.

Ref: GitHub Issue #22.
"""

from __future__ import annotations

import html
import tempfile
from collections import defaultdict
from pathlib import Path

from ctrlmap.models.schemas import (
    InsufficientEvidence,
    MappedResult,
    MappingRationale,
    ParsedChunk,
)

# ---------------------------------------------------------------------------
# CSS & JS — loaded from external template files
# ---------------------------------------------------------------------------

_TEMPLATES_DIR = Path(__file__).parent / "templates"


def _load_css() -> str:
    """Load the report stylesheet from ``templates/report.css``."""
    return (_TEMPLATES_DIR / "report.css").read_text(encoding="utf-8")


def _load_js() -> str:
    """Load the report script from ``templates/report.js``."""
    return (_TEMPLATES_DIR / "report.js").read_text(encoding="utf-8")


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def format_html(
    results: list[MappedResult],
    all_chunks: list[ParsedChunk] | None = None,
) -> str:
    """Format mapping results as a dual-tab interactive HTML page.

    Tab 1 — *Framework Gap Analysis*: one card per framework control.
    Tab 2 — *Policy Coverage*: one card per source document showing
    which controls each policy chunk satisfies.

    Args:
        results: List of MappedResult objects to format.
        all_chunks: Optional list of all extracted chunks. When provided,
            the Policy Coverage tab shows every chunk, not just matched ones.

    Returns:
        A complete HTML document string.
    """
    gap_html = _render_framework_gap_tab(results)
    cov_html = _render_policy_coverage_tab(results, all_chunks=all_chunks)

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>ctrlmap — Compliance Mapping Report</title>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link href="https://fonts.googleapis.com/css2?family=Inter\
:wght@400;500;600;700"
      rel="stylesheet">
<link href="https://fonts.googleapis.com/css2?family=JetBrains+Mono\
:wght@400;600"
      rel="stylesheet">
<style>{_load_css()}</style>
</head>
<body>
<h1>Compliance Mapping Report</h1>
<p class="subtitle">\
Generated by ctrlmap — policy-to-framework control mapping\
 with AI rationale</p>

<div class="tabs">
  <button class="tab-btn active" data-tab="framework-gap">\
Framework Gap Analysis</button>
  <button class="tab-btn" data-tab="policy-coverage">\
Policy Coverage</button>
</div>

<div id="framework-gap" class="tab-panel active">
{gap_html}
</div>

<div id="policy-coverage" class="tab-panel">
{cov_html}
</div>

<script>{_load_js()}</script>
</body>
</html>
"""


def export_html(
    results: list[MappedResult],
    path: Path,
    all_chunks: list[ParsedChunk] | None = None,
) -> None:
    """Write mapping results as an interactive HTML report to disk.

    Args:
        results: List of MappedResult objects to export.
        path: Output file path.
    """
    content = format_html(results, all_chunks=all_chunks)
    path.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile(
        mode="w",
        encoding="utf-8",
        dir=path.parent,
        suffix=".tmp",
        delete=False,
    ) as tmp:
        tmp.write(content)
        tmp_path = Path(tmp.name)
    tmp_path.rename(path)


# ---------------------------------------------------------------------------
# Tab 1: Framework Gap Analysis (control-centric)
# ---------------------------------------------------------------------------


def _render_framework_gap_tab(results: list[MappedResult]) -> str:
    """Build the content for the Framework Gap Analysis tab."""
    if not results:
        return '<div class="empty-msg">No mapping results to display.</div>'

    from ctrlmap.models.schemas import ComplianceLevel

    compliant = sum(
        1
        for r in results
        if isinstance(r.rationale, MappingRationale)
        and r.rationale.compliance_level == ComplianceLevel.FULLY_COMPLIANT
    )
    partial = sum(
        1
        for r in results
        if isinstance(r.rationale, MappingRationale)
        and r.rationale.compliance_level == ComplianceLevel.PARTIALLY_COMPLIANT
    )
    noncompliant = len(results) - compliant - partial

    stats = f"""
    <div class="stats-bar">
      <div class="stat">
        <div class="stat-value">{len(results)}</div>
        <div class="stat-label">Total Controls</div>
      </div>
      <div class="stat">
        <div class="stat-value" style="color:var(--green)">\
{compliant}</div>
        <div class="stat-label">Compliant</div>
      </div>
      <div class="stat">
        <div class="stat-value" style="color:var(--yellow)">\
{partial}</div>
        <div class="stat-label">Partial</div>
      </div>
      <div class="stat">
        <div class="stat-value" style="color:var(--red)">\
{noncompliant}</div>
        <div class="stat-label">Non-Compliant</div>
      </div>
    </div>
    """

    filters = """
    <div class="filters">
      <button class="filter-btn active" data-filter="all">\
All</button>
      <button class="filter-btn" data-filter="compliant">\
Compliant</button>
      <button class="filter-btn" data-filter="partial">\
Partial</button>
      <button class="filter-btn" data-filter="noncompliant">\
Non-Compliant</button>
    </div>
    """

    cards = "\n".join(_render_gap_card(r) for r in results)
    return f"{stats}\n{filters}\n{cards}"


def _render_gap_card(result: MappedResult) -> str:
    """Render one card for the Framework Gap tab."""
    ctrl = result.control
    vcls, vlbl, score = _classify_verdict(result.rationale)

    rows = []
    for i, c in enumerate(result.supporting_chunks, 1):
        src = html.escape(c.document_name)
        sec = html.escape(c.section_header or "\u2014")
        exc = html.escape(c.raw_text.replace("\n", " ").strip())
        rows.append(
            f"<tr><td>{i}</td>"
            f'<td class="source-doc">{src}</td>'
            f'<td class="page-num">{c.page_number}</td>'
            f'<td class="section-name">{sec}</td>'
            f'<td class="excerpt">{exc}</td></tr>'
        )

    ev = ""
    if rows:
        ev = (
            '<div class="evidence-label">Supporting Evidence</div>'
            "<table><thead><tr>"
            "<th>#</th><th>Source</th><th>Page</th>"
            "<th>Section</th><th>Excerpt</th>"
            "</tr></thead>"
            f"<tbody>{''.join(rows)}</tbody></table>"
        )

    _icon_clipboard = (
        '<svg width="14" height="14" viewBox="0 0 24 24" fill="none" '
        'stroke="currentColor" stroke-width="2" stroke-linecap="round" '
        'stroke-linejoin="round" style="vertical-align:-2px;margin-right:4px">'
        '<path d="M16 4h2a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H6a2 2 0 0 1'
        '-2-2V6a2 2 0 0 1 2-2h2"/>'
        '<rect x="8" y="2" width="8" height="4" rx="1" ry="1"/>'
        '<path d="M9 14l2 2 4-4"/></svg>'
    )
    _icon_sparkle = (
        '<svg width="14" height="14" viewBox="0 0 24 24" fill="none" '
        'stroke="currentColor" stroke-width="2" stroke-linecap="round" '
        'stroke-linejoin="round" style="vertical-align:-2px;margin-right:4px">'
        '<path d="M12 3l1.912 5.813a2 2 0 0 0 1.275 1.275L21 12l-5.813 '
        "1.912a2 2 0 0 0-1.275 1.275L12 21l-1.912-5.813a2 2 0 0 0-1.275"
        '-1.275L3 12l5.813-1.912a2 2 0 0 0 1.275-1.275L12 3z"/></svg>'
    )

    rat = ""
    rtxt = _get_rationale_text(result.rationale)
    if rtxt:
        rat = (
            f'<div class="evidence-label">{_icon_sparkle}AI Analysis</div>'
            f'<div class="rationale">{html.escape(rtxt)}</div>'
        )

    desc = html.escape(ctrl.description) if ctrl.description else ""
    desc_html = (
        f'<div class="evidence-label">{_icon_clipboard}'
        f"Framework Requirement</div>"
        f'<div class="ctrl-desc">{desc}</div>'
        if desc
        else ""
    )

    return f"""
    <div class="card" data-verdict="{vcls}">
      <div class="card-header">
        <span class="chevron">&#9654;</span>
        <span class="ctrl-id">{html.escape(ctrl.control_id)}</span>
        <span class="ctrl-title">{html.escape(ctrl.title)}</span>
        <span class="badge badge-{vcls}">{vlbl}</span>
        <span class="score">{score}</span>
      </div>
      <div class="card-body">
        <span class="framework-tag">\
{html.escape(ctrl.framework)}</span>
        {desc_html}
        {rat}
        {ev}
      </div>
    </div>
    """


# ---------------------------------------------------------------------------
# Tab 2: Policy Coverage (document-centric)
# ---------------------------------------------------------------------------


def _render_policy_coverage_tab(
    results: list[MappedResult],
    all_chunks: list[ParsedChunk] | None = None,
) -> str:
    """Build the content for the Policy Coverage tab.

    Shows ALL extracted chunks grouped by document. Chunks matched to
    framework controls display their control tags; unmatched chunks
    display an "Unmapped" tag.

    Args:
        results: Mapping results (used to build chunk→control index).
        all_chunks: Complete chunk list.  Falls back to only matched
            chunks when ``None``.
    """
    # Build an inverted index:  chunk_id → list of control labels
    chunk_controls: dict[str, list[str]] = defaultdict(list)
    # Also keep a unique-chunk registry  chunk_id → ParsedChunk
    chunk_registry: dict[str, ParsedChunk] = {}
    # Control info lookup:  label → (title, description)
    ctrl_info: dict[str, tuple[str, str]] = {}

    for result in results:
        ctrl = result.control
        label = f"{ctrl.framework} {ctrl.control_id}"
        ctrl_info[label] = (ctrl.title, ctrl.description or "")
        for chunk in result.supporting_chunks:
            chunk_controls[chunk.chunk_id].append(label)
            chunk_registry[chunk.chunk_id] = chunk

    # Use all_chunks when provided, falling back to matched-only
    if all_chunks:
        for chunk in all_chunks:
            if chunk.chunk_id not in chunk_registry:
                chunk_registry[chunk.chunk_id] = chunk

    if not chunk_registry:
        return '<div class="empty-msg">No mapping results to display.</div>'

    # Preserve extraction order: use position in all_chunks list
    order_index = {c.chunk_id: i for i, c in enumerate(all_chunks)} if all_chunks else {}

    # Group chunks by document_name
    docs: dict[str, list[ParsedChunk]] = defaultdict(list)
    seen: set[str] = set()
    for cid, chunk in chunk_registry.items():
        if cid not in seen:
            docs[chunk.document_name].append(chunk)
            seen.add(cid)

    # Sort by extraction order (index in all_chunks), falling back to page
    for chunks in docs.values():
        chunks.sort(key=lambda c: order_index.get(c.chunk_id, (c.page_number * 1000)))

    unique_docs = len(docs)
    total_chunks = len(chunk_registry)
    mapped_chunks = sum(1 for cid in chunk_registry if chunk_controls.get(cid))

    stats = f"""
    <div class="stats-bar">
      <div class="stat">
        <div class="stat-value">{unique_docs}</div>
        <div class="stat-label">Source Documents</div>
      </div>
      <div class="stat">
        <div class="stat-value">{total_chunks}</div>
        <div class="stat-label">Extracted Controls</div>
      </div>
      <div class="stat">
        <div class="stat-value" style="color:var(--green)">\
{mapped_chunks}</div>
        <div class="stat-label">Mapped to Framework</div>
      </div>
      <div class="stat">
        <div class="stat-value" style="color:var(--yellow)">\
{total_chunks - mapped_chunks}</div>
        <div class="stat-label">Unmapped</div>
      </div>
    </div>
    """

    cards = "\n".join(
        _render_coverage_card(doc_name, chunks, chunk_controls, ctrl_info)
        for doc_name, chunks in sorted(docs.items())
    )
    return f"{stats}\n{cards}"


def _render_coverage_card(
    doc_name: str,
    chunks: list[ParsedChunk],
    chunk_controls: dict[str, list[str]],
    ctrl_info: dict[str, tuple[str, str]],
) -> str:
    """Render one document card for the Policy Coverage tab.

    Chunks are displayed in extraction order with page separators,
    sequential numbering, and full control text.
    """
    # Collect all unique controls this document covers
    all_ctrls: set[str] = set()
    mapped_count = 0
    for c in chunks:
        ctrls_for_chunk = chunk_controls.get(c.chunk_id, [])
        all_ctrls.update(ctrls_for_chunk)
        if ctrls_for_chunk:
            mapped_count += 1

    sections_html = []
    current_page = -1

    for idx, chunk in enumerate(chunks, 1):
        # Page separator
        if chunk.page_number != current_page:
            current_page = chunk.page_number
            sections_html.append(
                f'<div class="page-separator"><span>Page {current_page}</span></div>'
            )

        ctrls = chunk_controls.get(chunk.chunk_id, [])
        if ctrls:
            tag_parts: list[str] = []
            for ctrl_id in sorted(set(ctrls)):
                title, desc = ctrl_info.get(ctrl_id, ("", ""))
                tooltip = html.escape(f"{title}: {desc}" if desc else title)
                tag_parts.append(
                    f'<span class="ctrl-tag" title="{tooltip}">{html.escape(ctrl_id)}</span>'
                )
            tags = "".join(tag_parts)
        else:
            tags = (
                '<span class="ctrl-tag" style="background:var(--yellow);color:#000">Unmapped</span>'
            )
        sec = html.escape(chunk.section_header or "\u2014")
        txt = html.escape(chunk.raw_text.replace("\n", " ").strip())
        sections_html.append(f"""
        <div class="chunk-section">
          <div class="chunk-meta">\
<span class="chunk-num">#{idx}</span> \
<em>{sec}</em></div>
          <div class="chunk-text">{txt}</div>
          <div>{tags}</div>
        </div>
        """)

    unmapped_count = len(chunks) - mapped_count

    return f"""
    <div class="card">
      <div class="card-header">
        <span class="chevron">&#9654;</span>
        <span class="ctrl-id">{html.escape(doc_name)}</span>
        <span class="ctrl-title">\
{len(chunks)} chunks · \
<span style="color:var(--green)">{mapped_count} mapped</span> · \
<span style="color:var(--yellow)">{unmapped_count} unmapped</span></span>
      </div>
      <div class="card-body">
        {"".join(sections_html)}
      </div>
    </div>
    """


# ---------------------------------------------------------------------------
# Shared helpers
# ---------------------------------------------------------------------------


def _classify_verdict(
    rationale: MappingRationale | InsufficientEvidence | None,
) -> tuple[str, str, str]:
    """Return (css_class, label, score_display) for a verdict."""
    if isinstance(rationale, MappingRationale):
        from ctrlmap.models.schemas import ComplianceLevel

        level = rationale.compliance_level
        score = f"{rationale.confidence_score:.2f}"
        if level == ComplianceLevel.FULLY_COMPLIANT:
            return ("compliant", "Compliant", score)
        if level == ComplianceLevel.PARTIALLY_COMPLIANT:
            return ("partial", "Partial", score)
        return ("noncompliant", "Non-Compliant", score)
    # Everything else is Non-Compliant: insufficient evidence or no evidence.
    return ("noncompliant", "Non-Compliant", "")


def _get_rationale_text(
    rationale: MappingRationale | InsufficientEvidence | None,
) -> str:
    """Extract the explanation text from a rationale."""
    if rationale is None:
        return ""
    if isinstance(rationale, MappingRationale):
        return rationale.explanation
    return rationale.reason


def _truncate(text: str, max_len: int = 150) -> str:
    """Truncate text to max_len characters, adding ellipsis if needed."""
    text = text.replace("\n", " ").strip()
    if len(text) <= max_len:
        return text
    return text[: max_len - 3] + "..."
