"""Self-contained interactive HTML report for compliance mapping results.

Produces a single ``.html`` file with embedded CSS and JS — no external
dependencies.  Three report modes in one page:

1. **Framework Gap Analysis** — one card per framework control showing
   which policy chunks support it and the LLM verdict.
2. **Policy Coverage** — one card per source document showing which
   framework controls each policy section satisfies.
3. **Document Reader** — a continuous reading view of each policy
   document with highlighted chunks and hover-to-view control mappings.

Multi-framework support: pass ``results_by_framework`` to combine
multiple frameworks into a single unified report.

Ref: GitHub Issue #22.
"""

from __future__ import annotations

import html
import json
import tempfile
from collections import defaultdict
from pathlib import Path

from ctrlmap.models.schemas import (
    ComplianceLevel,
    InsufficientEvidence,
    MappedResult,
    MappingRationale,
    ParsedChunk,
)

# ---------------------------------------------------------------------------
# CSS & JS — loaded from external template files
# ---------------------------------------------------------------------------

_TEMPLATES_DIR = Path(__file__).parent / "templates"


def _load_css() -> str:
    """Load the report stylesheet from ``templates/report.css``."""
    return (_TEMPLATES_DIR / "report.css").read_text(encoding="utf-8")


def _load_js() -> str:
    """Load the report script from ``templates/report.js``."""
    return (_TEMPLATES_DIR / "report.js").read_text(encoding="utf-8")


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def format_html(
    results: list[MappedResult] | None = None,
    all_chunks: list[ParsedChunk] | None = None,
    *,
    results_by_framework: dict[str, list[MappedResult]] | None = None,
    pdf_documents: list[Any] | None = None,
) -> str:
    """Format mapping results as a multi-tab interactive HTML page.

    Tab 1 — *Framework Gap Analysis*: one card per framework control.
    Tab 2 — *Policy Coverage*: one card per source document.
    Tab 3 — *Document Reader*: PDF viewer with highlighted chunks, or
            text-based fallback when PDFs are not available.

    Args:
        results: List of MappedResult objects (single-framework mode).
        all_chunks: Optional list of all extracted chunks for the
            Policy Coverage and Document Reader tabs.
        results_by_framework: Dict mapping framework names to result
            lists.  When provided, ``results`` is ignored.
        pdf_documents: Optional list of ``RenderedDocument`` objects
            from ``pdf_renderer.render_document()``.  When provided,
            the Document Reader shows actual PDF page images with
            interactive overlay highlights.

    Returns:
        A complete HTML document string.
    """
    # Normalize to multi-framework dict
    fw_results = _normalize_results(results, results_by_framework)
    is_multi = len(fw_results) > 1

    # Merge all results into a flat list for tabs that need it
    all_results = [r for rs in fw_results.values() for r in rs]

    gap_html = _render_framework_gap_tab(all_results, fw_results, is_multi)
    cov_html = _render_policy_coverage_tab(all_results, all_chunks=all_chunks)
    reader_html = _render_document_reader_tab(
        all_results, all_chunks=all_chunks, pdf_documents=pdf_documents,
    )

    fw_pills_html = _render_framework_pills(fw_results) if is_multi else ""

    search_html = """
    <div class="search-bar">
      <input type="text" id="search-box" placeholder="Search controls, policies, evidence…"
             aria-label="Search report">
      <kbd class="search-kbd" id="search-kbd">⌘K</kbd>
    </div>
    """

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>ctrlmap — Compliance Mapping Report</title>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link href="https://fonts.googleapis.com/css2?family=Inter\
:wght@400;500;600;700"
      rel="stylesheet">
<link href="https://fonts.googleapis.com/css2?family=JetBrains+Mono\
:wght@400;600"
      rel="stylesheet">
<style>{_load_css()}</style>
</head>
<body>
<h1>Compliance Mapping Report</h1>
<p class="subtitle">\
Generated by ctrlmap — policy-to-framework control mapping\
 with AI rationale</p>

{search_html}
{fw_pills_html}

<div class="tabs">
  <button class="tab-btn active" data-tab="framework-gap">\
<svg width="15" height="15" viewBox="0 0 24 24" fill="none" \
stroke="currentColor" stroke-width="2" stroke-linecap="round" \
stroke-linejoin="round" style="vertical-align:-2px;margin-right:6px">\
<path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/>\
<path d="m9 12 2 2 4-4"/></svg>\
Framework Gap Analysis</button>
  <button class="tab-btn" data-tab="policy-coverage">\
<svg width="15" height="15" viewBox="0 0 24 24" fill="none" \
stroke="currentColor" stroke-width="2" stroke-linecap="round" \
stroke-linejoin="round" style="vertical-align:-2px;margin-right:6px">\
<path d="m12.83 2.18a2 2 0 0 0-1.66 0L2.6 6.08a1 1 0 0 0 0 1.83\
l8.58 3.91a2 2 0 0 0 1.66 0l8.58-3.9a1 1 0 0 0 0-1.83Z"/>\
<path d="m6.08 9.5-3.5 1.6a1 1 0 0 0 0 1.81l8.6 3.91a2 2 0 0 0\
 1.65 0l8.58-3.9a1 1 0 0 0 0-1.83l-3.5-1.59"/>\
<path d="m6.08 14.5-3.5 1.6a1 1 0 0 0 0 1.81l8.6 3.91a2 2 0 0 0\
 1.65 0l8.58-3.9a1 1 0 0 0 0-1.83l-3.5-1.59"/></svg>\
Policy Coverage</button>
  <button class="tab-btn" data-tab="document-reader">\
<svg width="15" height="15" viewBox="0 0 24 24" fill="none" \
stroke="currentColor" stroke-width="2" stroke-linecap="round" \
stroke-linejoin="round" style="vertical-align:-2px;margin-right:6px">\
<path d="M15 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0\
 2-2V7Z"/><path d="M14 2v4a2 2 0 0 0 2 2h4"/>\
<path d="M10 13H8"/><path d="M16 17H8"/>\
<path d="M16 13h-2"/></svg>\
Document Reader</button>
</div>

<div id="framework-gap" class="tab-panel active">
{gap_html}
</div>

<div id="policy-coverage" class="tab-panel">
{cov_html}
</div>

<div id="document-reader" class="tab-panel">
{reader_html}
</div>

<script>{_load_js()}</script>
</body>
</html>
"""


def export_html(
    results: list[MappedResult],
    path: Path,
    all_chunks: list[ParsedChunk] | None = None,
    *,
    results_by_framework: dict[str, list[MappedResult]] | None = None,
    pdf_documents: list[Any] | None = None,
) -> None:
    """Write mapping results as an interactive HTML report to disk.

    Args:
        results: List of MappedResult objects to export.
        path: Output file path.
        all_chunks: Optional list of all chunks for coverage tabs.
        results_by_framework: Optional multi-framework dict.
        pdf_documents: Optional rendered PDF data for Document Reader.
    """
    content = format_html(
        results,
        all_chunks=all_chunks,
        results_by_framework=results_by_framework,
        pdf_documents=pdf_documents,
    )
    path.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile(
        mode="w",
        encoding="utf-8",
        dir=path.parent,
        suffix=".tmp",
        delete=False,
    ) as tmp:
        tmp.write(content)
        tmp_path = Path(tmp.name)
    tmp_path.rename(path)


# ---------------------------------------------------------------------------
# Input normalization
# ---------------------------------------------------------------------------


def _normalize_results(
    results: list[MappedResult] | None,
    results_by_framework: dict[str, list[MappedResult]] | None,
) -> dict[str, list[MappedResult]]:
    """Normalize inputs to a ``{framework: [results]}`` dict."""
    if results_by_framework is not None:
        return results_by_framework

    if results is None:
        return {}

    # Group single results list by framework
    grouped: dict[str, list[MappedResult]] = defaultdict(list)
    for r in results:
        grouped[r.control.framework].append(r)
    return dict(grouped)


# ---------------------------------------------------------------------------
# Framework pills (multi-framework only)
# ---------------------------------------------------------------------------


_FW_DISPLAY_NAMES: dict[str, str] = {
    "PCI-DSS": "PCI DSS",
    "NIST-800-53": "NIST 800-53",
}


def _fw_display_name(fw_id: str) -> str:
    """Convert a framework ID to a human-readable display name."""
    return _FW_DISPLAY_NAMES.get(fw_id, fw_id.replace("-", " "))


def _render_framework_pills(
    fw_results: dict[str, list[MappedResult]],
) -> str:
    """Render framework filter pills for multi-framework reports."""
    pills = ['<button class="fw-pill active" data-fw="all">All</button>']
    for fw_name in sorted(fw_results):
        count = len(fw_results[fw_name])
        display = _fw_display_name(fw_name)
        pills.append(
            f'<button class="fw-pill" data-fw="{html.escape(fw_name)}">'
            f"{html.escape(display)} ({count})</button>"
        )
    return f'<div class="fw-pills">{"".join(pills)}</div>'


# ---------------------------------------------------------------------------
# Tab 1: Framework Gap Analysis (control-centric)
# ---------------------------------------------------------------------------


def _render_framework_gap_tab(
    results: list[MappedResult],
    fw_results: dict[str, list[MappedResult]],
    is_multi: bool,
) -> str:
    """Build the content for the Framework Gap Analysis tab."""
    if not results:
        return '<div class="empty-msg">No mapping results to display.</div>'

    compliant = sum(
        1
        for r in results
        if isinstance(r.rationale, MappingRationale)
        and r.rationale.compliance_level == ComplianceLevel.FULLY_COMPLIANT
    )
    partial = sum(
        1
        for r in results
        if isinstance(r.rationale, MappingRationale)
        and r.rationale.compliance_level == ComplianceLevel.PARTIALLY_COMPLIANT
    )
    noncompliant = len(results) - compliant - partial

    stats = f"""
    <div class="stats-bar">
      <div class="stat">
        <div class="stat-value">{len(results)}</div>
        <div class="stat-label">Total Controls</div>
      </div>
      <div class="stat">
        <div class="stat-value" style="color:var(--green)">\
{compliant}</div>
        <div class="stat-label">Compliant</div>
      </div>
      <div class="stat">
        <div class="stat-value" style="color:var(--yellow)">\
{partial}</div>
        <div class="stat-label">Partial</div>
      </div>
      <div class="stat">
        <div class="stat-value" style="color:var(--red)">\
{noncompliant}</div>
        <div class="stat-label">Non-Compliant</div>
      </div>
    </div>
    """

    filters = """
    <div class="filters">
      <button class="filter-btn active" data-filter="all">\
All</button>
      <button class="filter-btn" data-filter="compliant">\
Compliant</button>
      <button class="filter-btn" data-filter="partial">\
Partial</button>
      <button class="filter-btn" data-filter="noncompliant">\
Non-Compliant</button>
    </div>
    """

    cards = "\n".join(_render_gap_card(r) for r in results)
    return f"{stats}\n{filters}\n{cards}"


def _render_gap_card(result: MappedResult) -> str:
    """Render one card for the Framework Gap tab."""
    ctrl = result.control
    vcls, vlbl, score = _classify_verdict(result.rationale)

    rows = []
    for i, c in enumerate(result.supporting_chunks, 1):
        src = html.escape(c.document_name)
        sec = html.escape(c.section_header or "\u2014")
        exc = html.escape(c.raw_text.replace("\n", " ").strip())
        rows.append(
            f"<tr><td>{i}</td>"
            f'<td class="source-doc">{src}</td>'
            f'<td class="page-num">{c.page_number}</td>'
            f'<td class="section-name">{sec}</td>'
            f'<td class="excerpt">{exc}</td></tr>'
        )

    ev = ""
    if rows:
        ev = (
            '<div class="evidence-label">Supporting Evidence</div>'
            "<table><thead><tr>"
            "<th>#</th><th>Source</th><th>Page</th>"
            "<th>Section</th><th>Excerpt</th>"
            "</tr></thead>"
            f"<tbody>{''.join(rows)}</tbody></table>"
        )

    _icon_clipboard = (
        '<svg width="14" height="14" viewBox="0 0 24 24" fill="none" '
        'stroke="currentColor" stroke-width="2" stroke-linecap="round" '
        'stroke-linejoin="round" style="vertical-align:-2px;margin-right:4px">'
        '<path d="M16 4h2a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H6a2 2 0 0 1'
        '-2-2V6a2 2 0 0 1 2-2h2"/>'
        '<rect x="8" y="2" width="8" height="4" rx="1" ry="1"/>'
        '<path d="M9 14l2 2 4-4"/></svg>'
    )
    _icon_sparkle = (
        '<svg width="14" height="14" viewBox="0 0 24 24" fill="none" '
        'stroke="currentColor" stroke-width="2" stroke-linecap="round" '
        'stroke-linejoin="round" style="vertical-align:-2px;margin-right:4px">'
        '<path d="M12 3l1.912 5.813a2 2 0 0 0 1.275 1.275L21 12l-5.813 '
        "1.912a2 2 0 0 0-1.275 1.275L12 21l-1.912-5.813a2 2 0 0 0-1.275"
        '-1.275L3 12l5.813-1.912a2 2 0 0 0 1.275-1.275L12 3z"/></svg>'
    )

    rat = ""
    rtxt = _get_rationale_text(result.rationale)
    if rtxt:
        rat = (
            f'<div class="evidence-label">{_icon_sparkle}AI Analysis</div>'
            f'<div class="rationale">{html.escape(rtxt)}</div>'
        )

    desc = html.escape(ctrl.description) if ctrl.description else ""
    desc_html = (
        f'<div class="evidence-label">{_icon_clipboard}'
        f"Framework Requirement</div>"
        f'<div class="ctrl-desc">{desc}</div>'
        if desc
        else ""
    )

    fw_attr = f' data-framework="{html.escape(ctrl.framework)}"'

    return f"""
    <div class="card" data-verdict="{vcls}"{fw_attr}>
      <div class="card-header">
        <span class="chevron">&#9654;</span>
        <span class="ctrl-id">{html.escape(ctrl.control_id)}</span>
        <span class="ctrl-title">{html.escape(ctrl.title)}</span>
        <span class="badge badge-{vcls}">{vlbl}</span>
        <span class="score">{score}</span>
      </div>
      <div class="card-body">
        <span class="framework-tag">\
{html.escape(_fw_display_name(ctrl.framework))}</span>
        {desc_html}
        {rat}
        {ev}
      </div>
    </div>
    """


# ---------------------------------------------------------------------------
# Tab 2: Policy Coverage (document-centric)
# ---------------------------------------------------------------------------


def _render_policy_coverage_tab(
    results: list[MappedResult],
    all_chunks: list[ParsedChunk] | None = None,
) -> str:
    """Build the content for the Policy Coverage tab.

    Shows ALL extracted chunks grouped by document. Chunks matched to
    framework controls display their control tags; unmatched chunks
    display an "Unmapped" tag.

    Args:
        results: Mapping results (used to build chunk→control index).
        all_chunks: Complete chunk list.  Falls back to only matched
            chunks when ``None``.
    """
    # Build an inverted index:  chunk_id → list of control labels
    chunk_controls: dict[str, list[str]] = defaultdict(list)
    # Also keep a unique-chunk registry  chunk_id → ParsedChunk
    chunk_registry: dict[str, ParsedChunk] = {}
    # Control info lookup:  label → (title, description)
    ctrl_info: dict[str, tuple[str, str]] = {}

    for result in results:
        ctrl = result.control
        label = f"{ctrl.framework} {ctrl.control_id}"
        ctrl_info[label] = (ctrl.title, ctrl.description or "")
        for chunk in result.supporting_chunks:
            chunk_controls[chunk.chunk_id].append(label)
            chunk_registry[chunk.chunk_id] = chunk

    # Use all_chunks when provided, falling back to matched-only
    if all_chunks:
        for chunk in all_chunks:
            if chunk.chunk_id not in chunk_registry:
                chunk_registry[chunk.chunk_id] = chunk

    if not chunk_registry:
        return '<div class="empty-msg">No mapping results to display.</div>'

    # Preserve extraction order: use position in all_chunks list
    order_index = {c.chunk_id: i for i, c in enumerate(all_chunks)} if all_chunks else {}

    # Group chunks by document_name
    docs: dict[str, list[ParsedChunk]] = defaultdict(list)
    seen: set[str] = set()
    for cid, chunk in chunk_registry.items():
        if cid not in seen:
            docs[chunk.document_name].append(chunk)
            seen.add(cid)

    # Sort by extraction order (index in all_chunks), falling back to page
    for chunks in docs.values():
        chunks.sort(key=lambda c: order_index.get(c.chunk_id, (c.page_number * 1000)))

    unique_docs = len(docs)
    total_chunks = len(chunk_registry)
    mapped_chunks = sum(1 for cid in chunk_registry if chunk_controls.get(cid))

    stats = f"""
    <div class="stats-bar">
      <div class="stat">
        <div class="stat-value">{unique_docs}</div>
        <div class="stat-label">Source Documents</div>
      </div>
      <div class="stat">
        <div class="stat-value">{total_chunks}</div>
        <div class="stat-label">Extracted Controls</div>
      </div>
      <div class="stat">
        <div class="stat-value" style="color:var(--green)">\
{mapped_chunks}</div>
        <div class="stat-label">Mapped to Framework</div>
      </div>
      <div class="stat">
        <div class="stat-value" style="color:var(--yellow)">\
{total_chunks - mapped_chunks}</div>
        <div class="stat-label">Unmapped</div>
      </div>
    </div>
    """

    cards = "\n".join(
        _render_coverage_card(doc_name, chunks, chunk_controls, ctrl_info)
        for doc_name, chunks in sorted(docs.items())
    )
    return f"{stats}\n{cards}"


def _render_coverage_card(
    doc_name: str,
    chunks: list[ParsedChunk],
    chunk_controls: dict[str, list[str]],
    ctrl_info: dict[str, tuple[str, str]],
) -> str:
    """Render one document card for the Policy Coverage tab.

    Chunks are displayed in extraction order with page separators,
    sequential numbering, and full control text.
    """
    # Collect all unique controls this document covers
    all_ctrls: set[str] = set()
    mapped_count = 0
    for c in chunks:
        ctrls_for_chunk = chunk_controls.get(c.chunk_id, [])
        all_ctrls.update(ctrls_for_chunk)
        if ctrls_for_chunk:
            mapped_count += 1

    sections_html = []
    current_page = -1

    for idx, chunk in enumerate(chunks, 1):
        # Page separator
        if chunk.page_number != current_page:
            current_page = chunk.page_number
            sections_html.append(
                f'<div class="page-separator"><span>Page {current_page}</span></div>'
            )

        ctrls = chunk_controls.get(chunk.chunk_id, [])
        if ctrls:
            tag_parts: list[str] = []
            for ctrl_id in sorted(set(ctrls)):
                title, desc = ctrl_info.get(ctrl_id, ("", ""))
                tooltip = html.escape(f"{title}: {desc}" if desc else title)
                tag_parts.append(
                    f'<span class="ctrl-tag" title="{tooltip}">{html.escape(ctrl_id)}</span>'
                )
            tags = "".join(tag_parts)
        else:
            tags = (
                '<span class="ctrl-tag" style="background:var(--yellow);color:#000">Unmapped</span>'
            )
        sec = html.escape(chunk.section_header or "\u2014")
        txt = html.escape(chunk.raw_text.replace("\n", " ").strip())
        sections_html.append(f"""
        <div class="chunk-section">
          <div class="chunk-meta">\
<span class="chunk-num">#{idx}</span> \
<em>{sec}</em></div>
          <div class="chunk-text">{txt}</div>
          <div>{tags}</div>
        </div>
        """)

    unmapped_count = len(chunks) - mapped_count

    return f"""
    <div class="card">
      <div class="card-header">
        <span class="chevron">&#9654;</span>
        <span class="ctrl-id">{html.escape(doc_name)}</span>
        <span class="ctrl-title">\
{len(chunks)} chunks · \
<span style="color:var(--green)">{mapped_count} mapped</span> · \
<span style="color:var(--yellow)">{unmapped_count} unmapped</span></span>
      </div>
      <div class="card-body">
        {"".join(sections_html)}
      </div>
    </div>
    """


# ---------------------------------------------------------------------------
# Tab 3: Document Reader (continuous reading with highlights)
# ---------------------------------------------------------------------------


def _render_document_reader_tab(
    results: list[MappedResult],
    all_chunks: list[ParsedChunk] | None = None,
    pdf_documents: list[object] | None = None,
) -> str:
    """Build the Document Reader tab content.

    When ``pdf_documents`` is provided, renders an actual PDF page
    viewer with overlay highlights.  Otherwise falls back to the text-
    based reader.

    Args:
        results: Mapping results (for chunk→control lookup).
        all_chunks: All extracted chunks.
        pdf_documents: Optional list of ``RenderedDocument`` objects.
    """
    # Build chunk→control index for overlay popover data
    chunk_controls: dict[str, list[str]] = defaultdict(list)
    ctrl_details: dict[str, dict[str, str]] = {}

    for result in results:
        ctrl = result.control
        label = f"{ctrl.framework} {ctrl.control_id}"
        vcls, vlbl, score = _classify_verdict(result.rationale)
        ctrl_details[label] = {
            "title": ctrl.title,
            "description": ctrl.description,
            "compliance": vlbl,
            "confidence": score,
            "rationale": _get_rationale_text(result.rationale),
            "css_class": vcls,
        }
        for chunk in result.supporting_chunks:
            chunk_controls[chunk.chunk_id].append(label)

    if pdf_documents:
        return _render_pdf_viewer(pdf_documents, chunk_controls, ctrl_details)
    return _render_text_reader(results, all_chunks, chunk_controls, ctrl_details)


def _render_pdf_viewer(
    pdf_documents: list[object],
    chunk_controls: dict[str, list[str]],
    ctrl_details: dict[str, dict[str, str]],
) -> str:
    """Render the PDF page-image viewer with overlay highlights."""
    # Document selector
    doc_options = []
    for idx, doc in enumerate(pdf_documents):
        selected = " selected" if idx == 0 else ""
        doc_options.append(
            f'<option value="pdf-doc-{idx}"{selected}>'
            f"{html.escape(doc.document_name)}</option>"  # type: ignore[union-attr]
        )

    selector = f"""
    <div class="pdf-toolbar">
      <select id="pdf-doc-selector" class="pdf-selector">
        {"".join(doc_options)}
      </select>
      <span class="pdf-toolbar-info" id="pdf-page-info"></span>
    </div>
    """

    # Render each document's pages
    doc_sections = []
    for idx, doc in enumerate(pdf_documents):
        display = "" if idx == 0 else ' style="display:none"'
        pages_html = []
        for rendered_page in doc.pages:  # type: ignore[union-attr]
            overlays_html = _render_page_overlays(
                rendered_page, chunk_controls, ctrl_details,
            )
            pages_html.append(f"""
            <div class="pdf-page" data-page="{rendered_page.page_number}">
              <div class="pdf-page-header">Page {rendered_page.page_number}</div>
              <div class="pdf-page-container" style="aspect-ratio: \
{rendered_page.width}/{rendered_page.height}">
                <img class="pdf-page-img"
                     src="data:image/png;base64,{rendered_page.image_b64}"
                     alt="Page {rendered_page.page_number}"
                     loading="lazy">
                {overlays_html}
              </div>
            </div>
            """)
        doc_sections.append(
            f'<div class="pdf-doc-pages" id="pdf-doc-{idx}"{display}>'
            f'{"".join(pages_html)}</div>'
        )

    # Detail panel (right side) — populated by JS on hover/click
    detail_panel = """
    <div class="pdf-detail-panel" id="pdf-detail-panel">
      <div class="pdf-detail-header">Control Mappings</div>
      <div class="pdf-detail-empty" id="pdf-detail-empty">
        <div class="pdf-detail-icon"><svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="11" cy="11" r="8"/><path d="m21 21-4.3-4.3"/></svg></div>
        <div>Hover or click a highlighted chunk to see its control mappings</div>
      </div>
      <div class="pdf-detail-content" id="pdf-detail-content"
           style="display:none"></div>
    </div>
    """

    return f"""
    {selector}
    <div class="pdf-split-layout">
      {detail_panel}
      <div class="pdf-pages-pane">
        {''.join(doc_sections)}
      </div>
    </div>
    """


def _render_page_overlays(
    rendered_page: object,
    chunk_controls: dict[str, list[str]],
    ctrl_details: dict[str, dict[str, str]],
) -> str:
    """Build overlay highlight divs for a single PDF page."""
    overlays = []
    for overlay in rendered_page.overlays:  # type: ignore[union-attr]
        clip = f";clip-path:{overlay.clip_path}" if overlay.clip_path else ""
        ctrls = overlay.controls or chunk_controls.get(overlay.chunk_id, [])
        if not ctrls:
            # Unmapped chunk
            overlays.append(f"""
            <div class="pdf-overlay pdf-overlay--unmapped"
                 style="left:{overlay.x_pct}%;top:{overlay.y_pct}%;\
width:{overlay.w_pct}%;height:{overlay.h_pct}%{clip}"
                 data-chunk-id="{html.escape(overlay.chunk_id)}">
            </div>
            """)
            continue

        # Determine compliance level for color
        classes = [ctrl_details.get(c, {}).get("css_class", "") for c in ctrls]
        if "noncompliant" in classes:
            color_cls = "pdf-overlay--noncompliant"
        elif "partial" in classes:
            color_cls = "pdf-overlay--partial"
        else:
            color_cls = "pdf-overlay--compliant"

        # Build popover data with all controls
        controls_data = []
        for ctrl_label in sorted(set(ctrls)):
            detail = ctrl_details.get(ctrl_label, {})
            controls_data.append({
                "id": ctrl_label,
                "title": detail.get("title", ""),
                "description": detail.get("description", ""),
                "compliance": detail.get("compliance", ""),
                "confidence": detail.get("confidence", ""),
                "rationale": detail.get("rationale", ""),
            })

        popover_json = html.escape(json.dumps(controls_data), quote=True)

        overlays.append(f"""
        <div class="pdf-overlay {color_cls} doc-reader-chunk--mapped"
             style="left:{overlay.x_pct}%;top:{overlay.y_pct}%;\
width:{overlay.w_pct}%;height:{overlay.h_pct}%{clip}"
             data-chunk-id="{html.escape(overlay.chunk_id)}"
             data-popover="{popover_json}">
        </div>
        """)

    return "".join(overlays)


def _render_text_reader(
    results: list[MappedResult],
    all_chunks: list[ParsedChunk] | None,
    chunk_controls: dict[str, list[str]],
    ctrl_details: dict[str, dict[str, str]],
) -> str:
    """Text-based document reader fallback (no PDF data available)."""
    chunk_registry: dict[str, ParsedChunk] = {}
    for result in results:
        for chunk in result.supporting_chunks:
            chunk_registry[chunk.chunk_id] = chunk

    if all_chunks:
        for chunk in all_chunks:
            if chunk.chunk_id not in chunk_registry:
                chunk_registry[chunk.chunk_id] = chunk

    if not chunk_registry:
        return '<div class="empty-msg">No documents to display.</div>'

    order_index = {c.chunk_id: i for i, c in enumerate(all_chunks)} if all_chunks else {}

    docs: dict[str, list[ParsedChunk]] = defaultdict(list)
    seen: set[str] = set()
    for cid, chunk in chunk_registry.items():
        if cid not in seen:
            docs[chunk.document_name].append(chunk)
            seen.add(cid)

    for chunks in docs.values():
        chunks.sort(key=lambda c: order_index.get(c.chunk_id, (c.page_number * 1000)))

    sections = []
    for doc_name in sorted(docs):
        chunks = docs[doc_name]
        chunk_html_parts = []
        current_page = -1

        for chunk in chunks:
            if chunk.page_number != current_page:
                current_page = chunk.page_number
                chunk_html_parts.append(
                    f'<div class="page-separator"><span>Page {current_page}</span></div>'
                )

            ctrls = chunk_controls.get(chunk.chunk_id, [])
            is_mapped = bool(ctrls)

            border_cls = "doc-reader-chunk--unmapped"
            if is_mapped:
                border_cls = "doc-reader-chunk--mapped"
                classes = [ctrl_details.get(c, {}).get("css_class", "") for c in ctrls]
                if "noncompliant" in classes:
                    border_cls += " doc-reader-border--noncompliant"
                elif "partial" in classes:
                    border_cls += " doc-reader-border--partial"
                else:
                    border_cls += " doc-reader-border--compliant"

            tags_html = ""
            if ctrls:
                tag_parts = []
                for ctrl_label in sorted(set(ctrls)):
                    detail = ctrl_details.get(ctrl_label, {})
                    popover_data = html.escape(
                        json.dumps({
                            "id": ctrl_label,
                            "title": detail.get("title", ""),
                            "compliance": detail.get("compliance", ""),
                            "confidence": detail.get("confidence", ""),
                            "explanation": detail.get("explanation", ""),
                        }),
                        quote=True,
                    )
                    tag_parts.append(
                        f'<span class="ctrl-tag" data-popover="{popover_data}">'
                        f"{html.escape(ctrl_label)}</span>"
                    )
                tags_html = f'<div class="doc-reader-tags">{"".join(tag_parts)}</div>'

            sec = html.escape(chunk.section_header or "")
            sec_html = f'<div class="doc-reader-section">{sec}</div>' if sec else ""
            txt = html.escape(chunk.raw_text.replace("\n", " ").strip())

            chunk_html_parts.append(f"""
            <div class="doc-reader-chunk {border_cls}">
              {sec_html}
              <div class="doc-reader-text">{txt}</div>
              {tags_html}
            </div>
            """)

        sections.append(f"""
        <div class="doc-reader-doc">
          <h3 class="doc-reader-title">{html.escape(doc_name)}</h3>
          {"".join(chunk_html_parts)}
        </div>
        """)

    return "\n".join(sections)


# ---------------------------------------------------------------------------
# Shared helpers
# ---------------------------------------------------------------------------


def _classify_verdict(
    rationale: MappingRationale | InsufficientEvidence | None,
) -> tuple[str, str, str]:
    """Return (css_class, label, score_display) for a verdict."""
    if isinstance(rationale, MappingRationale):
        level = rationale.compliance_level
        score = f"{rationale.confidence_score:.2f}"
        if level == ComplianceLevel.FULLY_COMPLIANT:
            return ("compliant", "Compliant", score)
        if level == ComplianceLevel.PARTIALLY_COMPLIANT:
            return ("partial", "Partial", score)
        return ("noncompliant", "Non-Compliant", score)
    # Everything else is Non-Compliant: insufficient evidence or no evidence.
    return ("noncompliant", "Non-Compliant", "")


def _get_rationale_text(
    rationale: MappingRationale | InsufficientEvidence | None,
) -> str:
    """Extract the explanation text from a rationale."""
    if rationale is None:
        return ""
    if isinstance(rationale, MappingRationale):
        return rationale.explanation
    return rationale.reason
